### ISSUE TITLE
Different button order on Mac compared to windows

### ISSUE THREAD

**Issue by martin1english** [tercen/flowjo_plugin#104]
![Button order on Mac](https://user-images.githubusercontent.com/64135638/168574379-ed998ed0-29f5-45b0-a041-bf0f16970f75.png)

A minor issue but it would be better if positions 1 and 3 were reversed.

**Comment by ginberg** [comment]
hi @martin1english I can change this but I am reading about this and the default button order on MAC OS seems different than on Windows, see https://stackoverflow.com/questions/12382281/why-are-the-options-reversed-in-my-joptionpane
Not sure you are aware of this but should I change it?

**Comment by martin1english** [comment]
Hi Ger, it is a minor issue and if we can't change (or change in some later build) then that is ok. 

If we can change then I think we should, as the order in the text list is different to the order of the buttons. 

These are Tercen functions rather than OS functions so I don't think there is an expectation from the Mac users.

**Comment by ginberg** [comment]
good point about the order in the text. I will update it in the next version

**Comment by ginberg** [comment]
Issue is not totally fixed. The buttons appear now in the right order, but:
- clicking on Return triggers the Import action and
- clicking on Import triggers the Return action
