### ISSUE TITLE
disable autoupdate

### ISSUE THREAD

**Issue by ginberg** [tercen/flowjo_plugin#107]
user should be notified if plugin version is not supported anymore and user should manually update

**Comment by ginberg** [comment]
related issues
#97 
#103 
#105

**Comment by martin1english** [comment]
@ginberg 
1.
Can you put a screen shot of the incompatibility popup message(s) for me.

2.
My understanding is that you can detect two possible "incompatible" states.
a. Plugin has a new version available and user installed plugin is still compatible with the server.
b. Plugin has a new version available and user installed plugin is **not compatible** with the server.

Is this true.

If so then we need 

Message A
**There is a new version of the Tercen plugin available. Install it from FlowJo Exchange and re-start FlowJo to take advantage of new features.** 
This should have an OK button which continues with the upload.
It should also have a check box for "Don't remind me again" 
(a good implementation of this would be that it resets when a new release is made and their plugin is now 2 behind the main version)

Message B
**Your Plugin version {version number} is no longer compatible with the Tercen server. We cannot upload your data. There is a new version of the Tercen plugin available. Install it from FlowJo Exchange and re-start FlowJo to take advantage of new features.**

**Comment by ginberg** [comment]
@martin1english this is the current message if the plugin detects it's not compatible anymore with the server. At the moment the plugin can't detect there is a new version, since in that case a connection with github has to be made (which fails for some users). We can only assume there is a new version, if the plugin of the user is not supported anymore..
![not_supported_message](https://user-images.githubusercontent.com/7089667/169502115-580a14a0-deb4-47b7-a0a3-d5f2defa48c7.png)

**Comment by ginberg** [comment]
should I change the current message to message B?

**Comment by martin1english** [comment]
If it not too much trouble can we change to.

**Oops! Your Plugin version {version number} is no longer compatible with the Tercen server. We cannot upload your data right now. Install the new version from FlowJo Exchange and re-start FlowJo to take advantage of new features.**

I would also make the button text say

**Cancel Upload** 


This way it is clear the plugin is not going to let them progress.
