### ISSUE TITLE
FlowJo plugin - how it should work with the iTeos Tercen platform

### ISSUE THREAD

**Issue by makostadima** [tercen/flowjo_plugin#110]
Having tested the plugin version 1.0.8 with the iTeos Tercen, I have the following requests:

- the plugin should not be trying to create a new account on iTeos Tercen
- it should test that the email address associated with the FlowJo license has the iteostherapeutics.com domain
- looks up on the iTeos Azure directory if the user exists and has access to the iteos Tercen platform
- if the user exists and has access, then use these credentials to connect to their iTeos Tercen account (SAML authentication)

This is a completely different design compared to the current one. But there are several iTeos employees really interested in the plugin, so there is a need for a different FlowJo plugn version that works with the iTeos Tercen Enterprise.

**Comment by ginberg** [comment]
I have discussed the approach with Alex M and started with the implementation of the new authentication method. It's in a new [branch](https://github.com/tercen/flowjo_plugin/tree/iteos) since it's not fully functional and I don't want to interfere with the plugin that we try to get deployed on the FlowJo exchange.

**Comment by ginberg** [comment]
hi @martin1english @makostadima, I created a new popup in case a user needs to authenticate via SAML. It should point the user to a website on tercen where the can copy&paste their token.
This is the page https://stage.tercen.com/_api-token

I am wondering about the exact text in the plugin. Do you have any suggestions? This is what I currently have

![saml_auth_popup](https://user-images.githubusercontent.com/7089667/178774919-e99cecb6-8655-4c70-acd7-de675544e15f.png)

**Comment by martin1english** [comment]
@ginberg 

## We are setting up your plugin network credentials.
### Please follow these steps

- Click this [authenticate](url) link to get a token.
- Copy the code displayed on the popup screen
- Paste it into the box below.
- Press Ok.

Token [ ###########]

_*Make the token text box bigger if you can._

**Comment by martin1english** [comment]
![image](https://user-images.githubusercontent.com/64135638/178940284-7520e8cc-3445-41b5-9c25-63edfacd07e9.png)

**Comment by ginberg** [comment]
thank you @martin1english ! I will update the plugin screen. The Tercen API page is made by Manu (it's on the sci repository). Could you create a separate issue for it in that repository?

**Comment by makostadima** [comment]
I have now tested v1.1.3 with the iTeos Tercen instance and it worked!
