### ISSUE TITLE
Failed to create an array of length more than 500000000

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#22]
I wanted to analyze some fcs files, with +/-1,000,000 cells each. I have 3 fcs files. 1 data file was ok to upload to Tercen, but 2nd and 3rd files failed because they become too big. Is this a Tercen limitation in general? Can this be bigger/grater? 

![Screenshot (88)](https://user-images.githubusercontent.com/87133370/133078657-0777ffec-6c1a-4810-a882-787c48c37f60.png)

**Comment by martin1english** [comment]
Tested ok.

**Comment by MahoNagasawa** [comment]
@martin1english I would like to be sure on this issue #22, you tested ok meaning there was no error anymore when you tried to upload a data points that will exceed the array length of 500,000,000?

**Comment by martin1english** [comment]
I uploaded the full FlowJo tutorial dataset at -1 on the properties file. This would have triggered the error message in the past but does not now.

**Comment by MahoNagasawa** [comment]
@martin1english 8 tutorial samples don't give this error because they are relatively small. This error shows up when I wanted to upload 3 files of 1,000,000 events with 12 channels, which is apparently 1,131,051,286 array length.  the limit of array length 500,000,000 is still there.  Tercen can't upload 3x 1,000,000 x 12 channels datapoints at once. too big. 1x 1,000,000x12 channels datapoints can. 2x1,000,000 x 12 channels fails. Thus this means, if someone wants to upload 1x 1,00,000 events x 24 channels amount of datapoints probably fail. That's somewhat disappointing.

**Comment by martin1english** [comment]
@MahoNagasawa  Thanks for pointing that out. It's my mistake. I was sure the tutorial data set gave the error in the past.

@amaurel @fnaji @ginberg does this mean that our properties file should be set to 500,000,000 (instead of the original 30,000,000). Is there a way to increase the array length and not trigger the error.

**Comment by ginberg** [comment]
@martin1english Faris came up with setting the max to 30,000,000. I think he wanted to set a lower max because one of the operators in our workflow take a long time with that many datapoints.

**Comment by martin1english** [comment]
@ginberg Yes that is true but in a later conversation we decided to take in the maximum amount of data Tercen is capable of and then handling the UMAP limitation with a down-sampling step in the workflows.
Our understanding is that the array bug is still in place (@MahoNagasawa tested it) and the maximum we can accept is 500,000,000 data points without triggering this error. But we are confused about this and not sure we have it correct. @amaurel would you be able to comment on what our max datapoint size is so we can set the plugin properties file to that amount.

**Comment by ginberg** [comment]
this has been fixed by Tercen upgrade
