### ISSUE TITLE
Only upload the compensated columns

### ISSUE THREAD

**Issue by ginberg** [tercen/flowjo_plugin#41]
right now we are uploading all the data, while only the compensated (selected) columns will be used. We can set the other columns to ignore, just as we can in the manual upload dialog.
See 
https://github.com/tercen/sci/blob/stage/sci_api_model/lib/src/model/impl/column_schema.dart#L26

**Comment by martin1english** [comment]
Related to issue #22

**Comment by ginberg** [comment]
just decided that we upload all columns

**Comment by ginberg** [comment]
closing this issue, because of #81
