### ISSUE TITLE
rename "filename"  to "population"

### ISSUE THREAD

**Issue by fnaji** [tercen/flowjo_plugin#56]
When you upload multiple populations, it uses a fixed name called "filename",  "population" is more exact.

**Comment by martin1english** [comment]
@MahoNagasawa  Can we close this issue? I don't know what to test.

**Comment by MahoNagasawa** [comment]
@martin1english if this is not back to "filename", some of the data steps gives error because the template was using "filename" . if this name is back to "filename" from "population" the red dot shouldn't appear anymore. Then we can close this issue.

**Comment by ginberg** [comment]
Maho confirmed that "filename" is back
