### ISSUE TITLE
Task.client.unknown error

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#73]
while running a test on v1.0.0 I got this error message. 

![image](https://user-images.githubusercontent.com/87133370/150352604-89208069-92d6-402f-9761-c2b8815a5666.png)

**Comment by ginberg** [comment]
hi @MahoNagasawa, good you are reporting it. This is an error of the Tercen platform not of the plugin. Do you have access to this repo? https://github.com/tercen/sci
If so, could you report it there? Otherwise I can do it.

**Comment by MahoNagasawa** [comment]
@ginberg I reported this in sci. I close this issue here.
