### ISSUE TITLE
error message: Socket closed

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#75]
We (Martin, Faris and me) were testing to unlimit the number of datapoints to be uploaded to Tercen by setting the number to -1 in the property document.

1st upload was stopped at the Tercen (stage) after opening the browser tab, it displayed Tercen Logo and circle of dots. 
2nd attempt encountered this error. 

![image](https://user-images.githubusercontent.com/87133370/150975639-ceb4c07e-8b85-427b-bace-2fe8d57bed7d.png)

**Comment by ginberg** [comment]
@MahoNagasawa this could happen if there is a connection problem or the server has a problem. Did you see this error just one time or regularly?

**Comment by MahoNagasawa** [comment]
ok. no, this was the first time.

**Comment by ginberg** [comment]
ok, then it seems to me not really a problem.
But maybe we should have a different message for the user?

**Comment by MahoNagasawa** [comment]
that would be nicer indeed, I won't be the only one who wouldn't understand what Socket closed error means.
