### ISSUE TITLE
bad request message: sign in failed for user 

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#76]
I get this view (Tercen logo page idling) and I just noticed that when it happens, it looks like sign in to Tercen failed during the data upload(error message is on the bottom, which I didn't realized this before) When this happens Tercen seems to fail to initiate the popup window for the template selection, However, the data is actually already uploaded because the project file is created and data is in the project file. 

![image](https://user-images.githubusercontent.com/87133370/151820808-c635bea1-e423-4a2f-8ce5-f0518496894b.png)

**Comment by MahoNagasawa** [comment]
@ginberg is this Tercen/sci issue?  then I will replace this there.

**Comment by ginberg** [comment]
@MahoNagasawa are you still seeing this now and then happening? I think it could be something related to the browser
