### ISSUE TITLE
Only upload Compensated Values.

### ISSUE THREAD

**Issue by martin1english** [tercen/flowjo_plugin#81]
Window 2

![image](https://user-images.githubusercontent.com/64135638/157287459-7bd9dbce-25d6-4355-838d-79e54da006c1.png)

Only show Compensated channels (the ones auto selected in blue) - Hide all other channels.

Only upload selected channels **not the full data set**

**Comment by martin1english** [comment]
@makostadima

**Comment by makostadima** [comment]
@ginberg as a clarification, this issue suprsedes issue #80 where it was asked to hide channel selection window behind button.

**Comment by ginberg** [comment]
@makostadima I already implemented #80. Can't we have the advanced button plus only showing the compensated channels (for now)?
