### ISSUE TITLE
Upload gathered & ungathered values.

### ISSUE THREAD

**Issue by makostadima** [tercen/flowjo_plugin#82]
Since it was decided to not upload all values, but only the selected compensated ones (see issue #81 ), it was also decided that we would like these values to be uploaded both in a long format (gathered), but also in a wide format.

The reason behind it is that the user can then make plots, where they plot one channel against another (like this [one](https://user-images.githubusercontent.com/1746464/157302774-e9eb7b08-d7d4-4f1f-aaae-fb2eaa590414.png)). Something that is not feasible only with the gathered values.

**Comment by ginberg** [comment]
hi @makostadima, so the plugin needs to upload the data twice? Why don't we add a workflow step to do the conversion?

**Comment by makostadima** [comment]
That's a very good point @ginberg! It would require that the workflows are updated to include a Gather step.

We need @fnaji input on this one, because it is true that it makes no sense to upload the data twice. Especially given that sometimes the data might be too large.

**Comment by makostadima** [comment]
@ginberg Martin, Maho, Faris and I will discuss this issue on Tuesday, 15 March. Please, put this on hold for the moment and leave the plugin as is with only the gathered values for now.

**Comment by ginberg** [comment]
hi @makostadima, is this issue still relevant you think or can we close it?

**Comment by makostadima** [comment]
Hello @ginberg. Apologies for the late reply. As we move forward with the FlowJo plugin and FACS analysis in general within Tercen, I believe that this is still relevant.

However, there hasn't been a specific need at the moment. Therefore, you could very well close it for now. But as I already said I believe that this is an issue and a discussion we will revisit relatively soon.

**Comment by ginberg** [comment]
ok @makostadima, I am closing it for now

**Comment by makostadima** [comment]
Just testing the new version (1.0.8) as we speak.

I will let you know as soon as I am done with it.

Myrto
