### ISSUE TITLE
plugin update issues

### ISSUE THREAD

**Issue by ginberg** [tercen/flowjo_plugin#84]
a couple of issues
- in some cases the progress bar is stuck at 0% (access denied message)
- in some cases the file is downloaded to wrong dir
![access_denied](https://user-images.githubusercontent.com/7089667/158394106-40bc7fde-328c-4be2-8df9-30170fcd707b.jpg)

**Comment by martin1english** [comment]
Text for error message.

**Oops, looks like we don't have permission to update the Tercen plugin automatically. Please download the new version from the FlowJo Exchange.**
