### ISSUE TITLE
use a multiple select component to specify which channels to upload

### ISSUE THREAD

**Issue by ginberg** [tercen/flowjo_plugin#89]
![mselect](https://user-images.githubusercontent.com/7089667/160797193-02966f8a-e74e-4906-870a-fa82f11a20ae.jpeg)

**Comment by fnaji** [comment]
Martin liked this one
![image](https://user-images.githubusercontent.com/5831788/160809790-4765860b-9f12-4a26-99f5-bc434b876b41.png)
