### ISSUE TITLE
GUI Changes for 1.0.6

### ISSUE THREAD

**Issue by martin1english** [tercen/flowjo_plugin#95]
![image](https://user-images.githubusercontent.com/64135638/166884081-e1e2b33a-2b50-47a8-b3d7-ed933afce0eb.png)

No changes.

************************************
**Initial Upload**

![image](https://user-images.githubusercontent.com/64135638/166884429-e5da0113-015a-4cf6-87ce-049e7e70adff.png)
1. Now that we have pivoted to concatenated files being the normal use case we need to switch the windows so the select FCS window is on the top and the file selector on the bottom.

2. If you can detect that there is only one file then the File selector window should be hidden.

************************************

**Double clicking the connector AFTER an initial upload.**

![image](https://user-images.githubusercontent.com/64135638/166886336-9542be20-2270-4f75-83cb-ac8f95d36394.png)

New popup screen
![image](https://user-images.githubusercontent.com/64135638/166886429-ea0f4296-a436-430a-82f5-db30df758977.png)

Button Actions
1. Return - opens Tercen as per previous Hyperlink option 
![image](https://user-images.githubusercontent.com/64135638/166886634-e0dcf7ee-8d55-4bc1-a432-31c0ece00552.png)

2. Open Upload Screen (with changes detailed above) to allow FCS channels selection.

3. Open export file selection panel (as per 1.0.x changes) as a stand alone popup without the return option or the select Files/FCS windows. (I don't have a screenshot)

**Comment by martin1english** [comment]
![image](https://user-images.githubusercontent.com/64135638/166965083-514c9bad-fea0-4c69-8e24-af9317d26f80.png)

##### Body Text
_Remove the Blue icon._

### Welcome Back
What's next for your data? Choose an option.

- **Return** - Open Tercen to resume working on my analysis project.
- **Upload Changes** - Create a new project with my recent changes.
- **Import** - Load a Tercen export file into this workspace.

***************Line************************

##### Button Text
Return
Upload Changes
Import


Do in the same style as the opening screen (except with three buttons)
![image](https://user-images.githubusercontent.com/64135638/166968846-f6d27632-ed3c-4797-b4f2-ad27cde5f8ee.png)

**Comment by martin1english** [comment]
Feedback on latest changes.

![image](https://user-images.githubusercontent.com/64135638/167099742-51904c6d-be85-4c7e-9d8a-db2140c2b096.png)




Text Change: Remove "Choose an option" from text line.

**Comment by martin1english** [comment]
![image](https://user-images.githubusercontent.com/64135638/167099837-de732c96-9723-47d0-bbe3-62198db861c6.png)

This panel is very old. Not up to date with Windows 10 is there a better one.

It is defaulting to the Documents folder where it should default to the Downloads folder.

**Comment by ginberg** [comment]
I added the whitelines in the popup screen and the default Downloads directory in the fileUpload.

The width of this popup depends on the content and because the intro popup has a longer description, that one is wider. We could add a dummy component to make them the same width but then we need to set a certain pixel value, I am not sure what we should set for this

**Comment by martin1english** [comment]
@ginberg Ok there is no need to get too complicated. We might make changes in version 2 later.
