### ISSUE TITLE
unexpected error run operator exit code 125

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#96]
during the v1.0.7, with 4 flowjo turotial fcs files, concatenated pop for Tercen upload, choose advanced workflow, run all, got stuck at data labeling step.

![image](https://user-images.githubusercontent.com/87133370/167580544-8c802c7f-80b5-4f67-a2a9-f22b256c0f86.png)

**Comment by ginberg** [comment]
it's related to tercen version 0.9.15
